name: Build Aliyun Docker Image CI

on:
    repository_dispatch:
        types: build
    push:
        branches:
            - master
        paths:
            - 'Dockerfile'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
            name: Checkout
            uses: actions/checkout@master
      -     
            name: Dockerhub login
            env:
                DOCKER_PASSWORD: ${{ secrets.ALIYUN_DOCKER_PASSWORD }}
                DOCKER_USERNAME: ${{ secrets.ALIYUN_DOCKER_USERNAME }}
            run: |
                echo "${DOCKER_PASSWORD}" | docker login --username ${DOCKER_USERNAME} registry.cn-shenzhen.aliyuncs.com --password-stdin
      -
            name: Build dockerfile (with push)

            run: |
                docker build -t registry.cn-shenzhen.aliyuncs.com/chenjunxinprojects/james-docker:v3.3.0 . \
                docker push registry.cn-shenzhen.aliyuncs.com/chenjunxinprojects/james-docker:v3.3.0
   

